name:                MLCAD23
version:             0.1.0.0
github:              "electronics-and-drives/MLCAD23"
license:             BSD3
author:              "Yannick Uhlmann"
maintainer:          "augustunderground@protonmail.com"
copyright:           "2023 Yannick Uhlmann"

extra-source-files:
- README.md
- ChangeLog.md

data-files:
- rsrc/testbench.scs

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/electronics-and-drives/MLCAD23#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- random
- lens
- mtl
- containers
- split
- constraints
- clock
- deepseq
- parallel
- async
- vector
- aeson
- yaml
- inline-c
- inline-c-cpp
- libtorch-ffi
- libtorch-ffi-helper
- hasktorch
- hasktorch-gradually-typed
- hnutmeg
- hspectre
- text
- bytestring
- unix
- temporary
- hvega
- ihaskell-hvega
- plotly-hs
- rando
- data-default-class
- moo
- breakpoint
- time
- hmatrix
- hmatrix-gsl
- scheduler
- optparse-applicative

library:
  source-dirs: src

executables:
  MLCAD23-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MLCAD23
    when:
    - condition: false
      other-modules: Paths_fuacide

tests:
  MLCAD23-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MLCAD23
